# Generated by Django 3.1.3 on 2020-11-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Name')),
                ('char_class', models.CharField(max_length=50, verbose_name='Character Class')),
                ('char_race', models.CharField(max_length=50, verbose_name='Character Race')),
                ('atk', models.IntegerField(verbose_name='Attack')),
                ('ac', models.IntegerField(verbose_name='Armor Class')),
                ('hp', models.IntegerField(verbose_name='Hit Points')),
                ('mgc', models.IntegerField(verbose_name='Magic')),
            ],
        ),
    ]
