# Generated by Django 3.1.3 on 2020-11-29 03:55

from django.db import migrations

def create_data(apps, schema_editor):
    Adventurer = apps.get_model('adventurers', 'Adventurer')
    Adventurer(name="Aelien",char_class="Warrior",char_race="Human",atk=10,ac=10,hp=10,mgc=10).save()


class Migration(migrations.Migration):

    dependencies = [
        ('adventurers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
